apiVersion: v2
name: my-hours
description: My Hours — Go API + Vue SPA umbrella Helm chart
type: application
version: 0.1.2
appVersion: "v0.1.2"
dependencies:
  - name: backend
    version: "*"
    repository: file://charts/backend
  - name: frontend
    version: "*"
    repository: file://charts/frontend
