// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, type_id, description, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type_id, description, start_time, end_time, created_at, updated_at
`

type CreateActivityParams struct {
	UserID      uuid.UUID     `json:"user_id"`
	TypeID      uuid.NullUUID `json:"type_id"`
	Description string        `json:"description"`
	StartTime   time.Time     `json:"start_time"`
	EndTime     time.Time     `json:"end_time"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.TypeID,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TypeID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities
WHERE id = $1 AND user_id = $2
`

type DeleteActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivity = `-- name: GetActivity :one
SELECT id, user_id, type_id, description, start_time, end_time, created_at, updated_at FROM activities
WHERE id = $1 AND user_id = $2
`

type GetActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, arg.ID, arg.UserID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TypeID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivitiesInRange = `-- name: ListActivitiesInRange :many
SELECT id, user_id, type_id, description, start_time, end_time, created_at, updated_at FROM activities
WHERE user_id = $1
  AND start_time >= $2
  AND start_time < $3
ORDER BY start_time
`

type ListActivitiesInRangeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

func (q *Queries) ListActivitiesInRange(ctx context.Context, arg ListActivitiesInRangeParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesInRange, arg.UserID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TypeID,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
SET type_id = $3,
    description = $4,
    start_time = $5,
    end_time = $6,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type_id, description, start_time, end_time, created_at, updated_at
`

type UpdateActivityParams struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	TypeID      uuid.NullUUID `json:"type_id"`
	Description string        `json:"description"`
	StartTime   time.Time     `json:"start_time"`
	EndTime     time.Time     `json:"end_time"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.ID,
		arg.UserID,
		arg.TypeID,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TypeID,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
