// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activity_types.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createActivityType = `-- name: CreateActivityType :one
INSERT INTO activity_types (user_id, name, color, sort)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, color, sort, created_at, updated_at
`

type CreateActivityTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Color  string    `json:"color"`
	Sort   int32     `json:"sort"`
}

func (q *Queries) CreateActivityType(ctx context.Context, arg CreateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, createActivityType,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Sort,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivityType = `-- name: DeleteActivityType :execrows
DELETE FROM activity_types
WHERE id = $1 AND user_id = $2
`

type DeleteActivityTypeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteActivityType(ctx context.Context, arg DeleteActivityTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivityType, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivityType = `-- name: GetActivityType :one
SELECT id, user_id, name, color, sort, created_at, updated_at FROM activity_types
WHERE id = $1 AND user_id = $2
`

type GetActivityTypeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActivityType(ctx context.Context, arg GetActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, getActivityType, arg.ID, arg.UserID)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityTypes = `-- name: ListActivityTypes :many
SELECT id, user_id, name, color, sort, created_at, updated_at FROM activity_types
WHERE user_id = $1
ORDER BY sort ASC, created_at ASC
`

func (q *Queries) ListActivityTypes(ctx context.Context, userID uuid.UUID) ([]ActivityType, error) {
	rows, err := q.db.Query(ctx, listActivityTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityType
	for rows.Next() {
		var i ActivityType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Sort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityType = `-- name: UpdateActivityType :one
UPDATE activity_types
SET name = $3,
    color = $4,
    sort = $5,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, color, sort, created_at, updated_at
`

type UpdateActivityTypeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Color  string    `json:"color"`
	Sort   int32     `json:"sort"`
}

func (q *Queries) UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) (ActivityType, error) {
	row := q.db.QueryRow(ctx, updateActivityType,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Sort,
	)
	var i ActivityType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.Sort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
