// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: day_notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDayNote = `-- name: DeleteDayNote :execrows
DELETE FROM day_notes
WHERE user_id = $1 AND note_date = $2
`

type DeleteDayNoteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	NoteDate time.Time `json:"note_date"`
}

func (q *Queries) DeleteDayNote(ctx context.Context, arg DeleteDayNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDayNote, arg.UserID, arg.NoteDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDayNote = `-- name: GetDayNote :one
SELECT id, user_id, note_date, content, created_at, updated_at FROM day_notes
WHERE user_id = $1 AND note_date = $2
`

type GetDayNoteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	NoteDate time.Time `json:"note_date"`
}

func (q *Queries) GetDayNote(ctx context.Context, arg GetDayNoteParams) (DayNote, error) {
	row := q.db.QueryRow(ctx, getDayNote, arg.UserID, arg.NoteDate)
	var i DayNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteDate,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDayNotesInRange = `-- name: ListDayNotesInRange :many
SELECT id, user_id, note_date, content, created_at, updated_at FROM day_notes
WHERE user_id = $1
  AND note_date >= $2
  AND note_date < $3
ORDER BY note_date
`

type ListDayNotesInRangeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

func (q *Queries) ListDayNotesInRange(ctx context.Context, arg ListDayNotesInRangeParams) ([]DayNote, error) {
	rows, err := q.db.Query(ctx, listDayNotesInRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayNote
	for rows.Next() {
		var i DayNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteDate,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDayNote = `-- name: UpsertDayNote :one
INSERT INTO day_notes (user_id, note_date, content)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, note_date)
DO UPDATE SET content = EXCLUDED.content, updated_at = now()
RETURNING id, user_id, note_date, content, created_at, updated_at
`

type UpsertDayNoteParams struct {
	UserID   uuid.UUID `json:"user_id"`
	NoteDate time.Time `json:"note_date"`
	Content  string    `json:"content"`
}

func (q *Queries) UpsertDayNote(ctx context.Context, arg UpsertDayNoteParams) (DayNote, error) {
	row := q.db.QueryRow(ctx, upsertDayNote, arg.UserID, arg.NoteDate, arg.Content)
	var i DayNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteDate,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
