// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: email_change_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailChangeToken = `-- name: CreateEmailChangeToken :one
INSERT INTO email_change_tokens (user_id, new_email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, new_email, token_hash, expires_at, created_at
`

type CreateEmailChangeTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	NewEmail  string    `json:"new_email"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeToken(ctx context.Context, arg CreateEmailChangeTokenParams) (EmailChangeToken, error) {
	row := q.db.QueryRow(ctx, createEmailChangeToken,
		arg.UserID,
		arg.NewEmail,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailChangeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailChangeToken = `-- name: DeleteEmailChangeToken :exec
DELETE FROM email_change_tokens
WHERE id = $1
`

func (q *Queries) DeleteEmailChangeToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailChangeToken, id)
	return err
}

const deleteEmailChangeTokensForUser = `-- name: DeleteEmailChangeTokensForUser :exec
DELETE FROM email_change_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailChangeTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailChangeTokensForUser, userID)
	return err
}

const getEmailChangeTokenByHash = `-- name: GetEmailChangeTokenByHash :one
SELECT id, user_id, new_email, token_hash, expires_at, created_at FROM email_change_tokens
WHERE token_hash = $1
`

func (q *Queries) GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (EmailChangeToken, error) {
	row := q.db.QueryRow(ctx, getEmailChangeTokenByHash, tokenHash)
	var i EmailChangeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
