// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateActivityType(ctx context.Context, arg CreateActivityTypeParams) (ActivityType, error)
	CreateEmailChangeToken(ctx context.Context, arg CreateEmailChangeTokenParams) (EmailChangeToken, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) (int64, error)
	DeleteActivityType(ctx context.Context, arg DeleteActivityTypeParams) (int64, error)
	DeleteDayNote(ctx context.Context, arg DeleteDayNoteParams) (int64, error)
	DeleteEmailChangeToken(ctx context.Context, id uuid.UUID) error
	DeleteEmailChangeTokensForUser(ctx context.Context, userID uuid.UUID) error
	DeletePasswordResetToken(ctx context.Context, id uuid.UUID) error
	DeletePasswordResetTokensForUser(ctx context.Context, userID uuid.UUID) error
	GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error)
	GetActivityType(ctx context.Context, arg GetActivityTypeParams) (ActivityType, error)
	GetDayNote(ctx context.Context, arg GetDayNoteParams) (DayNote, error)
	GetEmailChangeTokenByHash(ctx context.Context, tokenHash string) (EmailChangeToken, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActivitiesInRange(ctx context.Context, arg ListActivitiesInRangeParams) ([]Activity, error)
	ListActivityTypes(ctx context.Context, userID uuid.UUID) ([]ActivityType, error)
	ListDayNotesInRange(ctx context.Context, arg ListDayNotesInRangeParams) ([]DayNote, error)
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	UpdateActivityType(ctx context.Context, arg UpdateActivityTypeParams) (ActivityType, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertDayNote(ctx context.Context, arg UpsertDayNoteParams) (DayNote, error)
}

var _ Querier = (*Queries)(nil)
